config/routes.rb
Rails.application.routes.draw do
  resources :turmas

  devise_for :alunos, :controllers => {:registrations => "aluno/registrations", :sessions => "aluno/sessions" }
  devise_scope :alunos do
    get   'signup' => "aluno/registrations#new"
  end

  devise_for :professors, :controllers => {:registrations => "professor/registrations", :sessions => "professor/sessions" }
  devise_scope :professors do
    get   'signup' => "professor/registrations#new"
  end
  get 'secretario/signup' => "secretario/registrations#new"
  get 'secretarios', to: 'secretario#show_all'
  get 'professors', to: 'professor#show_all'
  get 'alunos', to: 'aluno#show_all'
  get 'secretario', to: 'secretario#index'
  get 'turmas', to: 'turmas#index'
  get 'professor', to: 'professor#index'
  get 'aluno', to: 'aluno#index'
  get 'aluno_historico', to: 'turmas#index'

  root 'home#inicio'
  namespace :secretario do
    root :to => "secretario#index"
  end
  namespace :professor do
    root :to => "professor#index"
  end
  namespace :aluno do
    root :to => "aluno#index"
  end

  devise_for :secretarios, :controllers => {:registrations => "secretario/registrations", :sessions => "secretario/sessions" }
  devise_scope :secretarios do
    get   'signup' => "secretario/registrations#new"
  end

  #devise_for :professors, :class_name => 'Professor', :controllers => {:registrations => "professor/professor" } do
   # get   "professor/sign_up" => "professor#new", :as => :private_customer_signup
  #end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/turma.rb
class Turma < ApplicationRecord
  belongs_to :professor
  has_many :alunos
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: [:show, :edit, :update, :destroy]

  # GET /turmas
  # GET /turmas.json
  def index
    @turmas = Turma.all
  end

  # GET /turmas/1
  # GET /turmas/1.json
  def show
  end

  # GET /turmas/new
  def new
    @turma = Turma.new
  end

  # GET /turmas/1/edit
  def edit
  end

  # POST /turmas
  # POST /turmas.json
  def create
    @turma = Turma.new(turma_params)

    respond_to do |format|
      if @turma.save
        format.html { redirect_to @turma, notice: 'Turma was successfully created.' }
        format.json { render :show, status: :created, location: @turma }
      else
        format.html { render :new }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turmas/1
  # PATCH/PUT /turmas/1.json
  def update
    respond_to do |format|
      if @turma.update(turma_params)
        format.html { redirect_to @turma, notice: 'Turma was successfully updated.' }
        format.json { render :show, status: :ok, location: @turma }
      else
        format.html { render :edit }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  def alunos_vinculados
    @turmas = Turma.all
  end
  # DELETE /turmas/1
  # DELETE /turmas/1.json
  def destroy
    @turma.destroy
    respond_to do |format|
      format.html { redirect_to turmas_url, notice: 'Turma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turma
      @turma = Turma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turma_params
      params.require(:turma).permit(:nome, :nivel, :horario, :professor_id)
    end


end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/views/turmas/_form.html.erb
<%= form_with(model: turma, local: true, html: { class: "navbar-form navbar-right form-inline" }) do |form| %>
  <% if turma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
        <% turma.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.text_field :nome, :placeholder => "Nome", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.number_field :nivel, :placeholder => "Nível", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.text_area :horario, :placeholder => "Horários", class: "form-control" %>
  </div>
  <% if professor_signed_in? %>
    <div class="form-group">
      <br />
      <%= form.label :professor %>
    <input class="form-control" type=number placeholder= <%= current_professor.nome%> readonly>
      <%= hidden_field_tag "turma[professor_id]", current_professor.id %>
      <br />
    </div>
  <% else %>
    <div class="form-group">
      <%= form.label :professor %><br />
      <%= collection_select(:turma, :professor_id, Professor.all, :id, :nome, :class => 'form-control') %>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/turmas/alunos_vinculados.html.erb
<p id="notice"><%= notice %></p>
<select class="selectpicker">
  <% @turmas.each do |turma| %>
    <option value="<%= turma.id %>"><%= turma.nome %></option>
  <% end %>
</select>

  <% if professor_signed_in? %>
    <h1>Minhas Turmas</h1>
  <% elsif secretario_signed_in? %>
    <h1>Todas as Turmas</h1>
  <% end %>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Nível</th>
      <th scope="col">Horário(s)</th>
      <th scope="col">Professor</th>
      <th scope="col">Mostrar</th>
      <th scope="col">Editar</th>
      <th scope="col">Excluir</th>
    </tr>
    </thead>
    <tbody>
    <% if professor_signed_in? %>
      <% @minhas_turmas = @turmas.where(professor_id: current_professor.id) %>
      <% @minhas_turmas.each do |turma| %>
        <tr>
          <td><h5><%= turma.nome %></h5></td>
          <td><h5><%= turma.nivel %></h5></td>
          <td><h5><%= turma.horario %></h5></td>
          <td><h5><%= turma.professor.nome %></h5></td>
          <td><%= link_to 'Show', turma , :class => "btn btn-success" , :style => "color:white"%></td>
          <td><%= link_to 'Edit', edit_turma_path(turma) , :class => "btn btn-warning" , :style => "color:white"%></td>
          <td><%= link_to 'Destroy', turma, :class => "btn btn-danger" , :style => "color:white", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% elsif secretario_signed_in? %>
      <% @turmas.each do |turma| %>
        <tr>
          <td><h5><%= turma.nome %></h5></td>
          <td><h5><%= turma.nivel %></h5></td>
          <td><h5><%= turma.horario %></h5></td>
          <td><h5><%= turma.professor.nome %></h5></td>
          <td><%= link_to 'Show', turma , :class => "btn btn-success" , :style => "color:white"%></td>
          <td><%= link_to 'Edit', edit_turma_path(turma) , :class => "btn btn-warning" , :style => "color:white"%></td>
          <td><%= link_to 'Destroy', turma, :class => "btn btn-danger" , :style => "color:white", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>

    </tbody>
  </table>
  <%= link_to 'Nova Turma', new_turma_path , :class => "btn btn-success", :style => "color:white"%>
</div>

app/views/turmas/edit.html.erb
<div id="container-login" class="container" style=" max-width: 400px; background-color: white;">
<h1>Editing Turma</h1>

<%= render 'form', turma: @turma %>


<%= link_to 'Show', @turma , :class => "btn btn-success" , :style => "color:white"%> |
<%= link_to 'Back', turmas_path , :class => "btn btn-primary" , :style => "color:white"%>
</div>

app/views/turmas/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container" style=" max-width: 800px; background-color: white;">
  <% if professor_signed_in? %>
    <h1>Minhas Turmas</h1>
  <% elsif secretario_signed_in? %>
    <h1>Todas as Turmas</h1>
  <% end %>
<table class="table">
  <thead>
  <tr>
    <th scope="col">Nome</th>
    <th scope="col">Nível</th>
    <th scope="col">Horário(s)</th>
    <th scope="col">Professor</th>
    <th scope="col">Mostrar</th>
    <th scope="col">Editar</th>
    <th scope="col">Excluir</th>
  </tr>
  </thead>
  <tbody>
  <% if professor_signed_in? %>
  <% @minhas_turmas = @turmas.where(professor_id: current_professor.id) %>
    <% @minhas_turmas.each do |turma| %>
      <tr>
        <td><h5><%= turma.nome %></h5></td>
        <td><h5><%= turma.nivel %></h5></td>
        <td><h5><%= turma.horario %></h5></td>
        <td><h5><%= turma.professor.nome %></h5></td>
        <td><%= link_to 'Show', turma , :class => "btn btn-success" , :style => "color:white"%></td>
        <td><%= link_to 'Edit', edit_turma_path(turma) , :class => "btn btn-warning" , :style => "color:white"%></td>
        <td><%= link_to 'Destroy', turma, :class => "btn btn-danger" , :style => "color:white", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% elsif secretario_signed_in? %>
    <% @turmas.each do |turma| %>
      <tr>
        <td><h5><%= turma.nome %></h5></td>
        <td><h5><%= turma.nivel %></h5></td>
        <td><h5><%= turma.horario %></h5></td>
        <td><h5><%= turma.professor.nome %></h5></td>
        <td><%= link_to 'Show', turma , :class => "btn btn-success" , :style => "color:white"%></td>
        <td><%= link_to 'Edit', edit_turma_path(turma) , :class => "btn btn-warning" , :style => "color:white"%></td>
        <td><%= link_to 'Destroy', turma, :class => "btn btn-danger" , :style => "color:white", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% end %>

  </tbody>
</table>
  <%= link_to 'Nova Turma', new_turma_path , :class => "btn btn-success", :style => "color:white"%>
</div>

app/views/turmas/new.html.erb
<div id="container-login" class="container" style=" max-width: 400px; background-color: white;">
<h1>New Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Back', turmas_path %>
</div>

app/views/turmas/show.html.erb

<div class="card" style="width: 500px;">
  <div class="card-header">
    Informações da Turma
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Nome: <%= @turma.nome %></li>
    <li class="list-group-item">Nível: <%= @turma.nivel %></li>
    <li class="list-group-item">Horários: <%= @turma.horario %></li>
    <li class="list-group-item">Professor: <%= @turma.professor.nome %></li>
  </ul>
  <%= link_to 'View/Add Alunos', '' , :class => "btn btn-success" , :style => "color:white", data: { confirm: 'Função não implementada!' }%>
  <%= link_to 'Edit', edit_turma_path(@turma), :class => "btn btn-warning" , :style => "color:white"%>
  <%= link_to 'Back', turmas_path , :class => "btn btn-primary" , :style => "color:white"%>

</div>