config/routes.rb
Rails.application.routes.draw do
  resources :turmas

  devise_for :alunos, :controllers => {:registrations => "aluno/registrations", :sessions => "aluno/sessions" }
  devise_scope :alunos do
    get   'signup' => "aluno/registrations#new"
  end

  devise_for :professors, :controllers => {:registrations => "professor/registrations", :sessions => "professor/sessions" }
  devise_scope :professors do
    get   'signup' => "professor/registrations#new"
  end
  get 'secretario/signup' => "secretario/registrations#new"
  get 'secretarios', to: 'secretario#show_all'
  get 'professors', to: 'professor#show_all'
  get 'alunos', to: 'aluno#show_all'
  get 'secretario', to: 'secretario#index'
  get 'turmas', to: 'turmas#index'
  get 'professor', to: 'professor#index'
  get 'aluno', to: 'aluno#index'
  get 'aluno_historico', to: 'turmas#index'

  root 'home#inicio'
  namespace :secretario do
    root :to => "secretario#index"
  end
  namespace :professor do
    root :to => "professor#index"
  end
  namespace :aluno do
    root :to => "aluno#index"
  end

  devise_for :secretarios, :controllers => {:registrations => "secretario/registrations", :sessions => "secretario/sessions" }
  devise_scope :secretarios do
    get   'signup' => "secretario/registrations#new"
  end

  #devise_for :professors, :class_name => 'Professor', :controllers => {:registrations => "professor/professor" } do
   # get   "professor/sign_up" => "professor#new", :as => :private_customer_signup
  #end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ep4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <% if secretario_signed_in? %>
          <%= link_to "UnB Idiomas", destroy_secretario_session_path, method: :delete, :class => "button btn btn-primary btn-lg navbar-btn", :style => "color:white"%>
        <% elsif professor_signed_in? %>
          <%= link_to "UnB Idiomas", destroy_professor_session_path, method: :delete, :class => "button btn btn-primary btn-lg navbar-btn", :style => "color:white"%>
        <% elsif aluno_signed_in? %>
          <%= link_to "UnB Idiomas", destroy_aluno_session_path, method: :delete, :class => "button btn btn-primary btn-lg navbar-btn", :style => "color:white"%>
        <% else %>
          <%= link_to "UnB Idiomas", "/", :class => "button btn btn-primary btn-lg navbar-btn", :style => "color:white"%>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <p class="navbar-text float-right">
          <% if secretario_signed_in? %>
            Logado como Secretário: <strong><%=  current_secretario.email %></strong>.
            <%= link_to 'Editar perfil', edit_secretario_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_secretario_session_path, method: :delete, :class => 'navbar-link'  %>
          <% elsif professor_signed_in? %>
            Logado como Professor: <strong><%=  current_professor.email %></strong>.
            <%= link_to 'Editar perfil', edit_professor_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_professor_session_path, method: :delete, :class => 'navbar-link'  %>
          <% elsif aluno_signed_in? %>
            Logado como Aluno: <strong><%=  current_aluno.email %></strong>.
            <%= link_to 'Editar perfil', edit_aluno_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_aluno_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Login", new_secretario_session_path, :class => 'navbar-link'  %>
          <% end %>
          </ul>
    </div>
  </nav>

  <body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>

</html>